config/routes.rb
Rails.application.routes.draw do
  root to: 'quotes#about'
  get 'qutoes/about', to: 'quotes#about', as: 'about'
  get 'quotes/quote_home', to: 'quotes#quote_home', as: 'quote_home'
  get 'quotes/index', to: 'quotes#index', as: 'index'
  get 'quotes/form', to: 'quotes#form', as: 'form'
  resources :quotes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :content, presence: true
  validates :author, presence: true
  validates :language, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def about
  end

  # create a new quote
  def form
    @quote = Quote.new
  end

  # create a new quote
  def create
    @quote = Quote.new
    @quote.content = params[:quote][:content]
    @quote.author = params[:quote][:author]
    @quote.language = params[:quote][:language]
    puts params[:quote]
    if @quote.save
      puts "new quote created"
      redirect_to form_path, notice: "New quote created."
    else
      redirect_to form_path, notice: "Error creating user."
    end
  end

  # get a single random quote from the database
  def quote_home
      quotes_list = Quote.all
      quoteNum = (0..quotes_list.length-1).to_a.shuffle.first
      @somequote = quotes_list[quoteNum]
  end

  # get the list of all of the quotes
  def index
    quotes_list = Quote.all
    @myquotes = quotes_list
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title> <%= yield(:title) %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <h1 > Quote Generator </h1>
    <%= button_to "About", about_path, method: :get, form: {style: 'display:inline-block;'}, class: 'my_button', :title=>"Click here to learn about this website."%>
    <%= button_to "Generate Quote", quote_home_path, method: :get, form: {style: 'display:inline-block;'},class: 'my_button',  :title=>"Click here to generate a quote." %>
    <%= button_to "Add Quote", form_path, method: :get, form: {style: 'display:inline-block;'}, class: 'my_button', :title=>"Click here to add a quote." %>
    <%= button_to "Quotes List", index_path, method: :get, form: {style: 'display:inline-block;'}, class: 'my_button', :title=>"Click here to see the entire database of quotes." %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/about.html.erb
<% provide(:title, "About the Quote Generator") %>
<h2> About</h2>
<p>This is a website for generating random quotes. These quotes draw from a variety of languages and sources. For example,
  there are French, English, and Russian quotes coming from a variety of people ranging from Eleanor Roosevelt to A.S. Pushkin.
The user can generate a random quote, add quotes to the database, or look at the available list of quotes in the database.
To generate a quote, click the "Generate Quote" button above. To add a quote click the "Add Quote" button above. To see the entire
list of quotes, click the "Quotes List" button above. </p>

app/views/quotes/form.html.erb
<h2>Add a Quote</h2>
<% provide(:title, "Add a Quote") %>
<%= form_for(@quote) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :author %>
  <%= f.text_field :author%>
  <%= f.label :language %>
  <%= f.text_field :language%>
  <%= f.submit%>
<% end %>

app/views/quotes/index.html.erb
<% provide(:title, "Quotes List") %>
<h2>Quotes List</h2>

<ul>

<% @myquotes.each do | quote | %>

<li align="left"><%= quote.content %> - <%=quote.author%> (<%=quote.language%>) </li>
<% end %>

</ul>

app/views/quotes/quote_home.html.erb
<% provide(:title, "Generate a Quote") %>
<h2>Generate a Quote</h2>

<p><big> <%= @somequote.content %></big> </p>
<p>- <%= @somequote.author %> (<%= @somequote.language %>)</p>
<p style="color:Gray"> <small><small> English quotes are taken from https://quotesnsmiles.com/quotes/77-of-the-worlds-most-popular-quotes/ or the user.</small> </small></p>
<p style="color:Gray"> <small><small> French quotes are taken from https://www.mon-poeme.fr/proverbes-francais-celebres/ or the user. </small></small></p>
<p style="color:Gray"> <small><small> Russian quotes are taken from https://russianpodcast.eu/famous-russian-quotes.html or the user. </small></small></p>
<p style="color:Gray"> <small><small> Any other quotes are from the user. </small></small></p>